### ISSUE TITLE
[GUI translation]  →  Nose Cone tool.

### ISSUE THREAD

**Issue by kaktusus** [davesrocketshop/Rocket#61]
```version of the workbench - 3.2.0```

Task panel of the `Nose Cone` tool.
Not all the labels have translations.

- General tab

  ![obraz](https://github.com/davesrocketshop/Rocket/assets/39754351/16ca503f-a9da-4da1-8c4d-cd8cb04e5b6f)
  
  1. `solid` - no string in Crowdin.
      https://crowdin.com/translate/freecad-addons/32156/en-pl?filter=basic&value=0#q=solid
  
  2.  `bar` - no string in Crowdin.
      https://crowdin.com/translate/freecad-addons/32156/en-pl?filter=basic&value=0#q=bar
  
  3.  `cross` - no string in Crowdin.
      https://crowdin.com/translate/freecad-addons/32156/en-pl?filter=basic&value=0#q=cross
  
  
  ![obraz](https://github.com/davesrocketshop/Rocket/assets/39754351/39855f3f-d1f5-4b20-bf7e-5c329099735f)
  
  
  1.  `sollid` - no string in Crowdin.
  
  2.  `hollow` - no string in Crowdin.
      https://crowdin.com/translate/freecad-addons/32156/en-pl?filter=basic&value=0#q=hollow
  
  3.  ` capped` - no string in Crowdin.
      https://crowdin.com/translate/freecad-addons/32156/en-pl?filter=basic&value=0#q=capped
  
  
  ![obraz](https://github.com/davesrocketshop/Rocket/assets/39754351/7c9d3d5d-86e3-4e8a-be0c-e55549bebea8)
 
  1.  `cone` - no string in Crowdin.
     https://crowdin.com/translate/freecad-addons/32156/en-pl?filter=basic&value=0#q=cone
  
  2.  `blunted cone` - no string in Crowdin.
      https://crowdin.com/translate/freecad-addons/32156/en-pl?filter=basic&value=0#q=blunted%20cone
  
  3.  `spherical` - no string in Crowdin.
      https://crowdin.com/translate/freecad-addons/32156/en-pl?filter=basic&value=0#q=spherical
  
  4.  `eliptical` - no string in Crowdin.
      https://crowdin.com/translate/freecad-addons/32156/en-pl?filter=basic&value=0#q=eliptical
  
  5.  `ogive` - no string in Crowdin.
      https://crowdin.com/translate/freecad-addons/32156/en-pl?filter=basic&value=0#q=ogive
  
  6.  `blunted ogive` - no string in Crowdin.
      https://crowdin.com/translate/freecad-addons/32156/en-pl?filter=basic&value=0#q=blunted%20ogive
  
  7.  `secant ogive` - no string in Crowdin.
      https://crowdin.com/translate/freecad-addons/32156/en-pl?filter=basic&value=0#q=secant%20ogive
  
  8.  `parabola` - no string in Crowdin.
      https://crowdin.com/translate/freecad-addons/32156/en-pl?filter=basic&value=0#q=parabola
  
  9.  `parabolic series` - no string in Crowdin.
      https://crowdin.com/translate/freecad-addons/32156/en-pl?filter=basic&value=0#q=parabolic%20series
  
  10.  `power series` - no string in Crowdin.
      https://crowdin.com/translate/freecad-addons/32156/en-pl?filter=basic&value=0#q=power%20series
  
  11.  `Von Karman` - no string in Crowdin.
      https://crowdin.com/translate/freecad-addons/32156/en-pl?filter=basic&value=0#q=Von%20Karman
  
  12.  `Hack series` - no string in Crowdin.
      https://crowdin.com/translate/freecad-addons/32156/en-pl?filter=basic&value=0#q=Hack%20series

- Material tab

  ![obraz](https://github.com/davesrocketshop/Rocket/assets/39754351/47f5c14c-a85e-403e-b05f-0d5f8da2dd83)
  The list is so long that I will not list all the items ....

**Comment by davesrocketshop** [comment]
Combo box translation code completed. Will be merged in the next release.

The material types are filenames. They will not be translated. The material system has a major rework planned, so it may be done there.
