### ISSUE TITLE
 [GUI translation] →  main menu / Rocket

### ISSUE THREAD

**Issue by kaktusus** [davesrocketshop/Rocket#62]
```version of the workbench - 3.2.0```

The menu label and some of the submenus do not have translators.

![obraz](https://github.com/davesrocketshop/Rocket/assets/39754351/a4c689ae-3654-4250-b5e8-0408337c1670)

1. `Rocket` - string is in Crowdin
    https://crowdin.com/translate/freecad-addons/32156/en-pl#6588168

2. ` Calculators` - string is in Crowdin
    https://crowdin.com/translate/freecad-addons/32156/en-pl#6588170

3. `Analysis` - string is in Crowdin
    https://crowdin.com/translate/freecad-addons/32156/en-pl#6600262

**Comment by davesrocketshop** [comment]
The translation code is in there, but the wrong translation function was being used.

**Comment by davesrocketshop** [comment]
![translation](https://github.com/davesrocketshop/Rocket/assets/38090157/4626f091-a183-4b23-8ef7-aef87417ca69)
